{% set name = "empyrical-reloaded" %}
{% set version = "0.5.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/empyrical-reloaded-{{ version }}.tar.gz
  sha256: 9d8163e301bdff411adef5e604547958a3a17122fc1274f6c9ae906f14ee5fb7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.9.2
    - bottleneck >=1.3.0
    - pandas >=1.0.0
    - scipy >=0.15.1
    - pandas-datareader >=0.4
    - yfinance >=0.1.63

test:
  requires:
    - python {{ python_min }}
  imports:
    - empyrical

about:
  home: https://pypi.org/project/empyrical-reloaded/
  summary: empyrical computes performance and risk statistics commonly used in quantitative finance
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stefan-jansen
